In [ ]:
import tensorflow as tf

In [ ]:
a = tf.constant([1, 2])
b = tf.constant([3, 4])

In [ ]:
c = tf.add(a, b)
c.numpy()

array([4, 6], dtype=int32)

In [ ]:
d = tf.subtract(a, b)
d.numpy()

array([-2, -2], dtype=int32)

In [ ]:
a_1 = tf.constant([[1, 2], [3, 4]])
b_1 = tf.constant([[2, 3], [4, 5]])

In [ ]:
m = tf.multiply(a_1, b_1)
m.numpy()

array([[ 2,  6],
       [12, 20]], dtype=int32)

In [ ]:
mm = tf.matmul(a_1, b_1)
mm.numpy()

array([[10, 13],
       [22, 29]], dtype=int32)

In [ ]:
d = tf.divide(a, b)
d.numpy()

array([0.33333333, 0.5       ])

In [ ]:
a = tf.constant([1,2,3,4,5,6])
a.shape

TensorShape([6])

In [ ]:
a = tf.reshape(a, shape=(2,3))
a.shape

TensorShape([2, 3])

In [ ]:
b = tf.expand_dims(a, -1)
b.shape

In [ ]:
b = tf.constant([[1,2],[3,4]])

In [ ]:
b = tf.square(b)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  1,  16],
       [ 81, 256]], dtype=int32)>

In [ ]:
from numpy import float32
b = tf.sqrt(tf.cast(b, dtype=float32))
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
min = tf.reduce_min(b, axis=None)
min.numpy()

np.float32(1.0)

In [ ]:
min = tf.reduce_min(b, axis=0)
min

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
max = tf.reduce_max(b, axis=1)
max

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
c = tf.constant([[1,2],[3,4.0]])

In [ ]:
avg = tf.reduce_mean(c)
avg.numpy()

np.float32(2.5)

In [ ]:
_sum = tf.reduce_sum(c)
_sum

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>